--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/lenlenlL6/Better-Myitem
build-by-default: true
branches:
- main
projects:
  Better-Myitem:
   icon: "469-4698437_pen-clipart-pixel-art-minecraft-pickaxe-transparent-background.png"
...
